### ISSUE TITLE
Grammar and Spelling

### ISSUE THREAD

**Issue by SofijaPechevska** [sedc-codecademy/sp2020-cp04-mkd#14]
@chris-t-yan 
**Summary:**
Grammar or spelling mistakes in the about us page.
**Steps to reproduce:**
Go to the menu - about us.
**Submit date:**
6/9/2020
**Priority:**
Low
**Severity:**
Low
**URL:**
https://sedc-codecademy.github.io/sp2020-cp04-mkd/src/pages/aboutUs-en.html
![Screenshot - 1](https://user-images.githubusercontent.com/63657258/84130115-221bcf00-aa43-11ea-9aaf-caee1a009ad4.png)
![Screenshot - 2](https://user-images.githubusercontent.com/63657258/84130213-44ade800-aa43-11ea-88cf-f9aa8c949101.png)
![Screenshot - 3](https://user-images.githubusercontent.com/63657258/84130225-49729c00-aa43-11ea-9e2c-2fc2f3603b91.png)
![Screenshot - 4](https://user-images.githubusercontent.com/63657258/84130245-50011380-aa43-11ea-984b-0870cf53eb62.png)
![Screenshot - 5](https://user-images.githubusercontent.com/63657258/84130270-57282180-aa43-11ea-8d6c-1be79ac6797d.png)
![Screenshot - 6](https://user-images.githubusercontent.com/63657258/84130286-5e4f2f80-aa43-11ea-81df-5c4afea31071.png)

**Comment by Capt-Titanium** [comment]
Can I work on this issue?
